
--
-- LibSQL SQL Schema dump automatic generated by geni
--

CREATE TABLE organizacion (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    mision TEXT,
    vision TEXT
, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE organizacion_equipo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organizacion_id INTEGER NOT NULL,
    nombre TEXT NOT NULL,
    cargo TEXT,
    rrss TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_org_equipo_organizacion FOREIGN KEY (organizacion_id)
    REFERENCES organizacion (id) ON DELETE CASCADE
);
CREATE TABLE evento (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organizacion_id INTEGER NOT NULL,
    nombre TEXT NOT NULL,
    descripcion TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, slug TEXT,
    CONSTRAINT fk_evento_organizacion FOREIGN KEY (organizacion_id)
    REFERENCES organizacion (id) ON DELETE CASCADE
);
CREATE TABLE evento_edicion_metrica (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento_edicion_id INTEGER NOT NULL,
    tipo TEXT NOT NULL,
    valor REAL,
    payload TEXT,
    fuente TEXT,
    fecha_registro TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notas TEXT,
    CONSTRAINT fk_metrica_evento_edicion FOREIGN KEY (evento_edicion_id)
    REFERENCES evento_edicion (id) ON DELETE CASCADE
);
CREATE TABLE evento_edicion_snapshot (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento_edicion_id INTEGER NOT NULL,
    tipo TEXT NOT NULL,
    payload TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    generado_en TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_snapshot_evento_edicion FOREIGN KEY (evento_edicion_id)
    REFERENCES evento_edicion (id) ON DELETE CASCADE,
    CONSTRAINT uq_snapshot UNIQUE (evento_edicion_id, tipo)
);
CREATE TABLE evento_edicion (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento_id INTEGER NOT NULL,
    nombre TEXT,
    numero_edicion TEXT NOT NULL,
    poster_url TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, slug TEXT,
    CONSTRAINT fk_evento_edicion_evento FOREIGN KEY (evento_id)
    REFERENCES evento (id) ON DELETE CASCADE
);
CREATE TABLE evento_edicion_dia (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento_edicion_id INTEGER NOT NULL,
    fecha TEXT NOT NULL,
    hora_inicio TEXT NOT NULL,
    hora_fin TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, lugar_id INTEGER REFERENCES lugar (id) ON DELETE SET NULL, modalidad TEXT NOT NULL DEFAULT 'presencial' CHECK (modalidad IN ('presencial', 'online', 'hibrido')),
    CONSTRAINT fk_evento_edicion_dia_edicion FOREIGN KEY (evento_edicion_id)
    REFERENCES evento_edicion (id) ON DELETE CASCADE,
    CONSTRAINT uq_evento_edicion_dia UNIQUE (evento_edicion_id, fecha)
);
CREATE TABLE lugar (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    direccion TEXT,
    coordenadas TEXT,
    url TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, ciudad TEXT,
    CONSTRAINT uq_lugar_nombre_direccion UNIQUE (nombre, direccion)
);
CREATE TABLE catalogo_artista (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    artista_id INTEGER NOT NULL UNIQUE,
    orden TEXT NOT NULL,
    destacado INTEGER NOT NULL DEFAULT 0,
    activo INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, descripcion TEXT,
    CONSTRAINT fk_catalogo_artista FOREIGN KEY (artista_id)
        REFERENCES artista (id) ON DELETE CASCADE,
    CONSTRAINT chk_catalogo_artista_destacado CHECK (destacado IN (0, 1)),
    CONSTRAINT chk_catalogo_artista_activo CHECK (activo IN (0, 1))
);
CREATE TABLE schema_migrations (id VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE artista_historial (id INTEGER PRIMARY KEY AUTOINCREMENT, artista_id INTEGER NOT NULL, pseudonimo TEXT, correo TEXT, rrss TEXT, ciudad TEXT, pais TEXT, orden INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, notas TEXT, CONSTRAINT fk_artista_historial_artista FOREIGN KEY (artista_id) REFERENCES artista (id) ON DELETE CASCADE, CONSTRAINT uq_artista_historial_orden UNIQUE (artista_id, orden), CONSTRAINT chk_artista_historial_orden CHECK (orden > 0), CONSTRAINT chk_artista_historial_has_data CHECK (pseudonimo IS NOT NULL OR correo IS NOT NULL OR rrss IS NOT NULL OR ciudad IS NOT NULL OR pais IS NOT NULL));
CREATE TABLE "evento_edicion_postulacion" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento_edicion_id INTEGER NOT NULL,
    nombre TEXT NOT NULL,
    pseudonimo TEXT,
    correo TEXT,
    rrss TEXT,
    disciplina_id INTEGER NOT NULL,
    dossier_url TEXT,
    estado TEXT NOT NULL DEFAULT 'pendiente',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_postulacion_evento_edicion 
        FOREIGN KEY (evento_edicion_id) REFERENCES evento_edicion (id) ON DELETE CASCADE,
    CONSTRAINT fk_postulacion_disciplina 
        FOREIGN KEY (disciplina_id) REFERENCES disciplina (id),
    CONSTRAINT chk_postulacion_estado 
        CHECK (estado IN ('pendiente', 'seleccionado', 'rechazado', 'invitado'))
);
CREATE TABLE "artista" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT,
    pseudonimo TEXT NOT NULL,
    correo TEXT,
    rrss TEXT,
    ciudad TEXT,
    pais TEXT,
    slug TEXT,
    estado_id INTEGER DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_artista_estado FOREIGN KEY (estado_id) REFERENCES artista_estado (id)
);
CREATE TABLE tipo_actividad (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT uq_tipo_actividad_nombre UNIQUE (nombre)
);
CREATE TABLE modo_ingreso (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    modo TEXT NOT NULL UNIQUE,
    descripcion TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE participante_exposicion (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    participante_id INTEGER NOT NULL,
    disciplina_id INTEGER NOT NULL,
    agrupacion_id INTEGER,
    modo_ingreso_id INTEGER NOT NULL DEFAULT 1,
    estado TEXT NOT NULL DEFAULT 'confirmado',
    notas TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_exposicion_participante 
        FOREIGN KEY (participante_id) REFERENCES evento_edicion_participante (id) ON DELETE CASCADE,
    CONSTRAINT fk_exposicion_disciplina 
        FOREIGN KEY (disciplina_id) REFERENCES disciplina (id),
    CONSTRAINT fk_exposicion_agrupacion 
        FOREIGN KEY (agrupacion_id) REFERENCES agrupacion (id),
    CONSTRAINT fk_exposicion_modo_ingreso 
        FOREIGN KEY (modo_ingreso_id) REFERENCES modo_ingreso (id),
    CONSTRAINT uq_exposicion_participante UNIQUE (participante_id),
    CONSTRAINT chk_exposicion_estado 
        CHECK (estado IN ('seleccionado', 'confirmado', 'cancelado', 'no_asistio'))
);
CREATE TABLE participante_actividad (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    participante_id INTEGER NOT NULL,
    tipo_actividad_id INTEGER NOT NULL,
    agrupacion_id INTEGER,
    modo_ingreso_id INTEGER NOT NULL DEFAULT 2,
    estado TEXT NOT NULL DEFAULT 'confirmado',
    notas TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_actividad_participante 
        FOREIGN KEY (participante_id) REFERENCES evento_edicion_participante (id) ON DELETE CASCADE,
    CONSTRAINT fk_actividad_tipo 
        FOREIGN KEY (tipo_actividad_id) REFERENCES tipo_actividad (id),
    CONSTRAINT fk_actividad_agrupacion 
        FOREIGN KEY (agrupacion_id) REFERENCES agrupacion (id),
    CONSTRAINT fk_actividad_modo_ingreso 
        FOREIGN KEY (modo_ingreso_id) REFERENCES modo_ingreso (id),
    CONSTRAINT chk_actividad_estado 
        CHECK (estado IN ('seleccionado', 'confirmado', 'cancelado', 'no_asistio'))
);
CREATE TABLE "evento_edicion_participante" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento_edicion_id INTEGER NOT NULL,
    artista_id INTEGER NOT NULL,
    estado TEXT NOT NULL DEFAULT 'confirmado',
    notas TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_participante_evento_edicion 
        FOREIGN KEY (evento_edicion_id) REFERENCES evento_edicion (id) ON DELETE CASCADE,
    CONSTRAINT fk_participante_artista 
        FOREIGN KEY (artista_id) REFERENCES artista (id) ON DELETE CASCADE,
    CONSTRAINT uq_participante UNIQUE (artista_id, evento_edicion_id),
    CONSTRAINT chk_participante_estado 
        CHECK (estado IN ('seleccionado', 'confirmado', 'cancelado', 'no_asistio'))
);
CREATE TABLE actividad (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    participante_actividad_id INTEGER NOT NULL,
    titulo TEXT,
    descripcion TEXT,
    duracion_minutos INTEGER,
    ubicacion TEXT,
    hora_inicio TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, cupos INTEGER,
    
    CONSTRAINT fk_actividad_participante_actividad 
        FOREIGN KEY (participante_actividad_id) REFERENCES participante_actividad (id) ON DELETE CASCADE,
    CONSTRAINT uq_actividad_participante_actividad UNIQUE (participante_actividad_id),
    CONSTRAINT chk_actividad_duracion CHECK (duracion_minutos IS NULL OR duracion_minutos > 0)
);
CREATE TABLE "disciplina" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slug TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "artista_estado" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    estado TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "agrupacion" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    correo TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "artista_imagen" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    artista_id INTEGER NOT NULL,
    imagen_url TEXT NOT NULL,
    tipo TEXT,
    orden INTEGER,
    metadata TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_artista_imagen_artista FOREIGN KEY (artista_id)
        REFERENCES artista (id) ON DELETE CASCADE
);
CREATE INDEX idx_evento_edicion_metrica_evento_edicion
ON evento_edicion_metrica (evento_edicion_id);
CREATE INDEX idx_evento_edicion_metrica_fecha
ON evento_edicion_metrica (fecha_registro);
CREATE INDEX idx_evento_edicion_snapshot_evento_edicion
ON evento_edicion_snapshot (evento_edicion_id);
CREATE INDEX idx_postulacion_evento_edicion ON evento_edicion_postulacion (evento_edicion_id);
CREATE INDEX idx_postulacion_disciplina ON evento_edicion_postulacion (disciplina_id);
CREATE INDEX idx_organizacion_equipo_organizacion ON organizacion_equipo (organizacion_id);
CREATE TRIGGER trg_organizacion_updated_at
AFTER UPDATE ON organizacion
FOR EACH ROW
BEGIN
    UPDATE organizacion SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_organizacion_equipo_updated_at
AFTER UPDATE ON organizacion_equipo
FOR EACH ROW
BEGIN
    UPDATE organizacion_equipo SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_evento_updated_at
AFTER UPDATE ON evento
FOR EACH ROW
BEGIN
    UPDATE evento SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_evento_edicion_updated_at
AFTER UPDATE ON evento_edicion
FOR EACH ROW
BEGIN
    UPDATE evento_edicion SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_evento_edicion_dia_updated_at
AFTER UPDATE ON evento_edicion_dia
FOR EACH ROW
BEGIN
    UPDATE evento_edicion_dia SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_lugar_updated_at
AFTER UPDATE ON lugar
FOR EACH ROW
BEGIN
    UPDATE lugar SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE UNIQUE INDEX idx_evento_slug ON evento (slug) WHERE slug IS NOT NULL;
CREATE UNIQUE INDEX idx_evento_edicion_numero 
ON evento_edicion (evento_id, numero_edicion);
CREATE UNIQUE INDEX idx_evento_edicion_slug 
ON evento_edicion (evento_id, slug);
CREATE TRIGGER trg_catalogo_artista_updated_at
AFTER UPDATE ON catalogo_artista
FOR EACH ROW
BEGIN
    UPDATE catalogo_artista SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE INDEX idx_catalogo_artista_orden ON catalogo_artista(orden);
CREATE INDEX idx_catalogo_artista_activo ON catalogo_artista(activo);
CREATE INDEX idx_catalogo_artista_destacado ON catalogo_artista(destacado);
CREATE INDEX idx_evento_edicion_evento ON evento_edicion (evento_id);
CREATE INDEX idx_evento_edicion_dia_edicion ON evento_edicion_dia (evento_edicion_id);
CREATE INDEX idx_evento_edicion_dia_fecha ON evento_edicion_dia (fecha);
CREATE INDEX idx_evento_edicion_dia_lugar ON evento_edicion_dia (lugar_id);
CREATE INDEX idx_artista_historial_artista ON artista_historial (artista_id);
CREATE INDEX idx_artista_historial_pseudonimo ON artista_historial (pseudonimo) WHERE pseudonimo IS NOT NULL;
CREATE INDEX idx_artista_historial_orden ON artista_historial (artista_id, orden);
CREATE TRIGGER trg_evento_edicion_postulacion_updated_at
AFTER UPDATE ON evento_edicion_postulacion
FOR EACH ROW
BEGIN
    UPDATE evento_edicion_postulacion SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE UNIQUE INDEX idx_artista_slug ON artista (slug) WHERE slug IS NOT NULL;
CREATE UNIQUE INDEX idx_artista_correo_pseudonimo ON artista (correo, pseudonimo) WHERE correo IS NOT NULL;
CREATE TRIGGER trg_tipo_actividad_updated_at
AFTER UPDATE ON tipo_actividad
FOR EACH ROW
BEGIN
    UPDATE tipo_actividad SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE INDEX idx_exposicion_participante ON participante_exposicion (participante_id);
CREATE INDEX idx_exposicion_disciplina ON participante_exposicion (disciplina_id);
CREATE INDEX idx_exposicion_agrupacion ON participante_exposicion (agrupacion_id);
CREATE INDEX idx_exposicion_estado ON participante_exposicion (estado);
CREATE TRIGGER trg_participante_exposicion_updated_at
AFTER UPDATE ON participante_exposicion
FOR EACH ROW
BEGIN
    UPDATE participante_exposicion SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE INDEX idx_actividad_participante ON participante_actividad (participante_id);
CREATE INDEX idx_actividad_tipo ON participante_actividad (tipo_actividad_id);
CREATE INDEX idx_actividad_agrupacion ON participante_actividad (agrupacion_id);
CREATE INDEX idx_actividad_estado ON participante_actividad (estado);
CREATE TRIGGER trg_participante_actividad_updated_at
AFTER UPDATE ON participante_actividad
FOR EACH ROW
BEGIN
    UPDATE participante_actividad SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE INDEX idx_participante_evento_edicion ON evento_edicion_participante (evento_edicion_id);
CREATE INDEX idx_participante_artista ON evento_edicion_participante (artista_id);
CREATE INDEX idx_participante_estado ON evento_edicion_participante (estado);
CREATE INDEX idx_exposicion_modo_ingreso ON participante_exposicion (modo_ingreso_id);
CREATE INDEX idx_actividad_modo_ingreso ON participante_actividad (modo_ingreso_id);
CREATE TRIGGER trg_modo_ingreso_updated_at
AFTER UPDATE ON modo_ingreso
FOR EACH ROW
BEGIN
    UPDATE modo_ingreso SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_evento_edicion_participante_updated_at
AFTER UPDATE ON evento_edicion_participante
FOR EACH ROW
BEGIN
    UPDATE evento_edicion_participante SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE INDEX idx_actividad_participante_actividad ON actividad (participante_actividad_id);
CREATE TRIGGER trg_actividad_updated_at
AFTER UPDATE ON actividad
FOR EACH ROW
BEGIN
    UPDATE actividad SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_artista_updated_at
AFTER UPDATE ON artista
FOR EACH ROW
BEGIN
    UPDATE artista SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_disciplina_updated_at
AFTER UPDATE ON disciplina
FOR EACH ROW
BEGIN
    UPDATE disciplina SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_artista_estado_updated_at
AFTER UPDATE ON artista_estado
FOR EACH ROW
BEGIN
    UPDATE artista_estado SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_agrupacion_updated_at
AFTER UPDATE ON agrupacion
FOR EACH ROW
BEGIN
    UPDATE agrupacion SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE INDEX idx_artista_imagen_artista ON artista_imagen (artista_id);
CREATE INDEX idx_artista_estado ON artista (estado_id);
CREATE TRIGGER trg_artista_imagen_updated_at
AFTER UPDATE ON artista_imagen
FOR EACH ROW
BEGIN
    UPDATE artista_imagen SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;