
--
-- LibSQL SQL Schema dump automatic generated by geni
--

CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE organizacion (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    mision TEXT,
    vision TEXT
, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE organizacion_equipo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organizacion_id INTEGER NOT NULL,
    nombre TEXT NOT NULL,
    cargo TEXT,
    rrss TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_org_equipo_organizacion FOREIGN KEY (organizacion_id)
    REFERENCES organizacion (id) ON DELETE CASCADE
);
CREATE TABLE evento (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organizacion_id INTEGER NOT NULL,
    nombre TEXT NOT NULL,
    descripcion TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, slug TEXT,
    CONSTRAINT fk_evento_organizacion FOREIGN KEY (organizacion_id)
    REFERENCES organizacion (id) ON DELETE CASCADE
);
CREATE TABLE disciplina (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL UNIQUE
, created_at TEXT, updated_at TEXT);
CREATE TABLE artista_imagen (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    artista_id INTEGER NOT NULL,
    imagen_url TEXT NOT NULL,
    tipo TEXT,
    orden INTEGER,
    metadata TEXT, created_at TEXT, updated_at TEXT,
    CONSTRAINT fk_artista_imagen_artista FOREIGN KEY (artista_id)
    REFERENCES artista (id) ON DELETE CASCADE
);
CREATE TABLE evento_edicion_postulacion (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento_edicion_id INTEGER NOT NULL,
    nombre TEXT NOT NULL,
    pseudonimo TEXT,
    correo TEXT,
    rrss TEXT,
    disciplina_id INTEGER NOT NULL,
    dossier_url TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_postulacion_evento_edicion FOREIGN KEY (evento_edicion_id)
    REFERENCES evento_edicion (id) ON DELETE CASCADE,
    CONSTRAINT fk_postulacion_disciplina FOREIGN KEY (disciplina_id)
    REFERENCES disciplina (id)
);
CREATE TABLE agrupacion (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    descripcion TEXT
, correo TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE agrupacion_miembro (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    agrupacion_id INTEGER NOT NULL,
    artista_id INTEGER NOT NULL,
    evento_edicion_id INTEGER NOT NULL, created_at TEXT, updated_at TEXT,
    CONSTRAINT fk_agrupacion_miembro_agrupacion FOREIGN KEY (agrupacion_id)
    REFERENCES agrupacion (id) ON DELETE CASCADE,
    CONSTRAINT fk_agrupacion_miembro_artista FOREIGN KEY (artista_id)
    REFERENCES artista (id) ON DELETE CASCADE,
    CONSTRAINT fk_agrupacion_miembro_evento_edicion FOREIGN KEY (evento_edicion_id)
    REFERENCES evento_edicion (id) ON DELETE CASCADE,
    CONSTRAINT uq_agrupacion_miembro UNIQUE (artista_id, evento_edicion_id)
);
CREATE TABLE evento_edicion_participante (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento_edicion_id INTEGER NOT NULL,
    artista_id INTEGER NOT NULL,
    disciplina_id INTEGER NOT NULL,
    agrupacion_id INTEGER,
    estado TEXT NOT NULL,
    notas TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_participante_evento_edicion FOREIGN KEY (evento_edicion_id)
    REFERENCES evento_edicion (id) ON DELETE CASCADE,
    CONSTRAINT fk_participante_artista FOREIGN KEY (artista_id)
    REFERENCES artista (id) ON DELETE CASCADE,
    CONSTRAINT fk_participante_disciplina FOREIGN KEY (disciplina_id)
    REFERENCES disciplina (id),
    CONSTRAINT fk_participante_agrupacion FOREIGN KEY (agrupacion_id)
    REFERENCES agrupacion (id),
    CONSTRAINT uq_participante UNIQUE (artista_id, evento_edicion_id),
    CONSTRAINT chk_evento_edicion_participante_estado CHECK (
        estado IN ('postulado', 'seleccionado', 'confirmado', 'rechazado', 'cancelado')
    )
);
CREATE TABLE artista_invitado (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    correo TEXT,
    rrss TEXT
, created_at TEXT, updated_at TEXT);
CREATE TABLE evento_edicion_invitado (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento_edicion_id INTEGER NOT NULL,
    artista_invitado_id INTEGER NOT NULL,
    rol TEXT NOT NULL,
    notas TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invitado_evento_edicion FOREIGN KEY (evento_edicion_id)
    REFERENCES evento_edicion (id) ON DELETE CASCADE,
    CONSTRAINT fk_invitado_artista FOREIGN KEY (artista_invitado_id)
    REFERENCES artista_invitado (id) ON DELETE CASCADE,
    CONSTRAINT chk_evento_edicion_invitado_rol CHECK (LENGTH(TRIM(rol)) > 0)
);
CREATE TABLE evento_edicion_metrica (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento_edicion_id INTEGER NOT NULL,
    tipo TEXT NOT NULL,
    valor REAL,
    payload TEXT,
    fuente TEXT,
    fecha_registro TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notas TEXT,
    CONSTRAINT fk_metrica_evento_edicion FOREIGN KEY (evento_edicion_id)
    REFERENCES evento_edicion (id) ON DELETE CASCADE
);
CREATE TABLE evento_edicion_snapshot (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento_edicion_id INTEGER NOT NULL,
    tipo TEXT NOT NULL,
    payload TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    generado_en TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_snapshot_evento_edicion FOREIGN KEY (evento_edicion_id)
    REFERENCES evento_edicion (id) ON DELETE CASCADE,
    CONSTRAINT uq_snapshot UNIQUE (evento_edicion_id, tipo)
);
CREATE INDEX idx_participante_evento_edicion
ON evento_edicion_participante (evento_edicion_id);
CREATE INDEX idx_participante_artista
ON evento_edicion_participante (artista_id);
CREATE INDEX idx_participante_estado
ON evento_edicion_participante (estado);
CREATE INDEX idx_agrupacion_miembro_evento_edicion
ON agrupacion_miembro (evento_edicion_id);
CREATE INDEX idx_agrupacion_miembro_agrupacion
ON agrupacion_miembro (agrupacion_id);
CREATE INDEX idx_evento_edicion_invitado_evento_edicion
ON evento_edicion_invitado (evento_edicion_id);
CREATE INDEX idx_evento_edicion_metrica_evento_edicion
ON evento_edicion_metrica (evento_edicion_id);
CREATE INDEX idx_evento_edicion_metrica_fecha
ON evento_edicion_metrica (fecha_registro);
CREATE INDEX idx_evento_edicion_snapshot_evento_edicion
ON evento_edicion_snapshot (evento_edicion_id);
CREATE TRIGGER trg_organizacion_updated_at
AFTER UPDATE ON organizacion
FOR EACH ROW
BEGIN
    UPDATE organizacion SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_organizacion_equipo_updated_at
AFTER UPDATE ON organizacion_equipo
FOR EACH ROW
BEGIN
    UPDATE organizacion_equipo SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_evento_updated_at
AFTER UPDATE ON evento
FOR EACH ROW
BEGIN
    UPDATE evento SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_evento_edicion_invitado_updated_at
AFTER UPDATE ON evento_edicion_invitado
FOR EACH ROW
BEGIN
    UPDATE evento_edicion_invitado SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_evento_edicion_participante_updated_at
AFTER UPDATE ON evento_edicion_participante
FOR EACH ROW
BEGIN
    UPDATE evento_edicion_participante SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_evento_edicion_postulacion_updated_at
AFTER UPDATE ON evento_edicion_postulacion
FOR EACH ROW
BEGIN
    UPDATE evento_edicion_postulacion SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_disciplina_updated_at
AFTER UPDATE ON disciplina
FOR EACH ROW
BEGIN
    UPDATE disciplina SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_disciplina_created_at
AFTER INSERT ON disciplina
FOR EACH ROW
WHEN NEW.created_at IS NULL
BEGIN
    UPDATE disciplina SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;
CREATE TRIGGER trg_artista_imagen_updated_at
AFTER UPDATE ON artista_imagen
FOR EACH ROW
BEGIN
    UPDATE artista_imagen SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_artista_imagen_created_at
AFTER INSERT ON artista_imagen
FOR EACH ROW
WHEN NEW.created_at IS NULL
BEGIN
    UPDATE artista_imagen SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;
CREATE TRIGGER trg_artista_invitado_updated_at
AFTER UPDATE ON artista_invitado
FOR EACH ROW
BEGIN
    UPDATE artista_invitado SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_artista_invitado_created_at
AFTER INSERT ON artista_invitado
FOR EACH ROW
WHEN NEW.created_at IS NULL
BEGIN
    UPDATE artista_invitado SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;
CREATE TRIGGER trg_agrupacion_updated_at
AFTER UPDATE ON agrupacion
FOR EACH ROW
BEGIN
    UPDATE agrupacion SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_agrupacion_created_at
AFTER INSERT ON agrupacion
FOR EACH ROW
WHEN NEW.created_at IS NULL
BEGIN
    UPDATE agrupacion SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;
CREATE TRIGGER trg_agrupacion_miembro_updated_at
AFTER UPDATE ON agrupacion_miembro
FOR EACH ROW
BEGIN
    UPDATE agrupacion_miembro SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TRIGGER trg_agrupacion_miembro_created_at
AFTER INSERT ON agrupacion_miembro
FOR EACH ROW
WHEN NEW.created_at IS NULL
BEGIN
    UPDATE agrupacion_miembro SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;
CREATE TABLE evento_edicion (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento_id INTEGER NOT NULL,
    nombre TEXT,
    numero_edicion TEXT NOT NULL,
    poster_url TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, slug TEXT,
    CONSTRAINT fk_evento_edicion_evento FOREIGN KEY (evento_id)
    REFERENCES evento (id) ON DELETE CASCADE
);
CREATE TRIGGER trg_evento_edicion_updated_at
AFTER UPDATE ON evento_edicion
FOR EACH ROW
BEGIN
    UPDATE evento_edicion SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TABLE evento_edicion_dia (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    evento_edicion_id INTEGER NOT NULL,
    fecha TEXT NOT NULL,
    hora_inicio TEXT NOT NULL,
    hora_fin TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, lugar_id INTEGER REFERENCES lugar (id) ON DELETE SET NULL, modalidad TEXT NOT NULL DEFAULT 'presencial' CHECK (modalidad IN ('presencial', 'online', 'hibrido')),
    CONSTRAINT fk_evento_edicion_dia_edicion FOREIGN KEY (evento_edicion_id)
    REFERENCES evento_edicion (id) ON DELETE CASCADE,
    CONSTRAINT uq_evento_edicion_dia UNIQUE (evento_edicion_id, fecha)
);
CREATE TRIGGER trg_evento_edicion_dia_updated_at
AFTER UPDATE ON evento_edicion_dia
FOR EACH ROW
BEGIN
    UPDATE evento_edicion_dia SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE TABLE lugar (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    direccion TEXT,
    coordenadas TEXT,
    url TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, ciudad TEXT,
    CONSTRAINT uq_lugar_nombre_direccion UNIQUE (nombre, direccion)
);
CREATE TRIGGER trg_lugar_updated_at
AFTER UPDATE ON lugar
FOR EACH ROW
BEGIN
    UPDATE lugar SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE UNIQUE INDEX idx_evento_slug ON evento (slug) WHERE slug IS NOT NULL;
CREATE UNIQUE INDEX idx_evento_edicion_numero 
ON evento_edicion (evento_id, numero_edicion);
CREATE UNIQUE INDEX idx_evento_edicion_slug 
ON evento_edicion (evento_id, slug);
CREATE TABLE catalogo_artista (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    artista_id INTEGER NOT NULL UNIQUE,
    orden TEXT NOT NULL,
    destacado INTEGER NOT NULL DEFAULT 0,
    activo INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, descripcion TEXT,
    CONSTRAINT fk_catalogo_artista FOREIGN KEY (artista_id)
        REFERENCES artista (id) ON DELETE CASCADE,
    CONSTRAINT chk_catalogo_artista_destacado CHECK (destacado IN (0, 1)),
    CONSTRAINT chk_catalogo_artista_activo CHECK (activo IN (0, 1))
);
CREATE TRIGGER trg_catalogo_artista_updated_at
AFTER UPDATE ON catalogo_artista
FOR EACH ROW
BEGIN
    UPDATE catalogo_artista SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
CREATE INDEX idx_catalogo_artista_orden ON catalogo_artista(orden);
CREATE INDEX idx_catalogo_artista_activo ON catalogo_artista(activo);
CREATE INDEX idx_catalogo_artista_destacado ON catalogo_artista(destacado);
CREATE TABLE schema_migrations (id VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE INDEX idx_evento_edicion_evento ON evento_edicion (evento_id);
CREATE INDEX idx_evento_edicion_dia_edicion ON evento_edicion_dia (evento_edicion_id);
CREATE INDEX idx_evento_edicion_dia_fecha ON evento_edicion_dia (fecha);
CREATE INDEX idx_artista_imagen_artista ON artista_imagen (artista_id);
CREATE INDEX idx_evento_edicion_dia_lugar ON evento_edicion_dia (lugar_id);
CREATE TABLE artista_historial (id INTEGER PRIMARY KEY AUTOINCREMENT, artista_id INTEGER NOT NULL, pseudonimo TEXT, correo TEXT, rrss TEXT, ciudad TEXT, pais TEXT, orden INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, notas TEXT, CONSTRAINT fk_artista_historial_artista FOREIGN KEY (artista_id) REFERENCES artista (id) ON DELETE CASCADE, CONSTRAINT uq_artista_historial_orden UNIQUE (artista_id, orden), CONSTRAINT chk_artista_historial_orden CHECK (orden > 0), CONSTRAINT chk_artista_historial_has_data CHECK (pseudonimo IS NOT NULL OR correo IS NOT NULL OR rrss IS NOT NULL OR ciudad IS NOT NULL OR pais IS NOT NULL));
CREATE INDEX idx_artista_historial_artista ON artista_historial (artista_id);
CREATE INDEX idx_artista_historial_pseudonimo ON artista_historial (pseudonimo) WHERE pseudonimo IS NOT NULL;
CREATE INDEX idx_artista_historial_orden ON artista_historial (artista_id, orden);
CREATE TABLE "artista" (id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT, pseudonimo TEXT NOT NULL, correo TEXT, rrss TEXT, ciudad TEXT, pais TEXT, created_at TEXT, updated_at TEXT, slug TEXT);
CREATE UNIQUE INDEX idx_artista_slug ON artista (slug);